version: '3.9'
services:
    php-apache:
        image: apache2.4/php5.4.45:0.0.1
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        volumes:
            - http-data:/var/www/html
            - type: bind
              source: /MC/MC00000/conf/www/index.php
              target: /var/www/html/index.php
            - type: bind
              source: /MC/MC00000/conf/www/index2.php
              target: /var/www/html/index2.php
            - type: bind
              source: /MC/MC00000/conf/www/cert/www.market-control.cloud.pem
              target: /etc/ssl/certs/www.market-control.cloud.pem
            - type: bind
              source: /MC/MC00000/conf/www/cert/www.market-control.cloud.key
              target: /etc/ssl/private/www.market-control.cloud.key	
        networks:
            - traefik-public
            - NetBE
        deploy:
          resources:
            limits:
             cpus: '0.50'
             memory: 1024M
            reservations:
             cpus: '0.25'
             memory: 512M
          labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.constraint-label=traefik-public
            - traefik.http.routers.${PLATFORM?Variable not set}-http.rule=Host(`${PLATFORM?Variable not set}.market-control.cloud`)
            - traefik.http.routers.${PLATFORM?Variable not set}-http.entrypoints=http
            - traefik.http.routers.${PLATFORM?Variable not set}-http.middlewares=https-redirect
            - traefik.http.routers.${PLATFORM?Variable not set}-https.rule=Host(`${PLATFORM?Variable not set}.market-control.cloud`)
            - traefik.http.routers.${PLATFORM?Variable not set}-https.entrypoints=https
            - traefik.http.routers.${PLATFORM?Variable not set}-https.tls=true
            - traefik.http.routers.${PLATFORM?Variable not set}-https.tls.certresolver=le
            - traefik.http.services.${PLATFORM?Variable not set}.loadbalancer.server.port=80
    mariadb:
        image: mariadb:10.4
        volumes:
            - maria-data:/var/lib/mysql
            - type: bind
              source: /MC/MC00000/conf/mariadb/my.cnf
              target: /etc/mysql/my.cnf    
        environment:
            TZ: "America/New York"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "marketcontrol"
            MYSQL_USER: 'marketcontrol'
            MYSQL_PASSWORD: 'marketcontrol'
            MYSQL_DATABASE: 'marketcontrol'
        ports:
            - target: 3306
              published: 3306
              protocol: tcp
              mode: host
        networks:
            - NetBE
volumes:
  http-data:
    driver: local
  maria-data:
    driver: local
networks:
  #FrontEnd Network
  traefik-public:
    external: true
  #BackEnd Network
  NetBE:
    driver: overlay
    attachable: true
